#Kotlin
kotlin.code.style=official
# Оставляем повышенную память для компилятора Kotlin IR
kotlin.daemon.jvmargs=-Xmx6g -XX:+UseG1GC

#Gradle
# Оставляем выделение 8 ГБ оперативной памяти
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -XX:+UseG1GC

    # Отключаем Configuration Cache, так как Kotlin/JS JS-задачи не умеют в него сохраняться
org.gradle.configuration-cache=false

# Отключаем Configuration on Demand по требованию компилятора Kotlin/JS
org.gradle.configureondemand=false

# Включаем обычный кэш (он полностью стабилен и безопасен)
org.gradle.caching=true

# Включаем параллельное выполнение модулей (оно будет работать корректно без on-demand)
org.gradle.parallel=true

# Инкрементальная компиляция JS
kotlin.incremental.js=true
